### ISSUE TITLE
PTMeXchange web changes

### ISSUE THREAD

**Issue by isbluis** [PRIDE-Archive/px-web-app#3]
Hi @ypriverol .   Thank you for giving me access to the repository.

I have updated the content for the PTMeXchange webpage; can you please push the "green button" to deploy when you get the chance?  Or let me know if there is a process for doing it myself instead.

Cheers.

**Comment by ypriverol** [comment]
@isbluis Thanks a lot, I will look into it deployment now.

**Comment by ypriverol** [comment]
Deployed https://www.proteomexchange.org/ptmxchange/index.html

**Comment by ypriverol** [comment]
I will close the issue.

**Comment by edeutsch** [comment]
Looks great, thanks. Maybe we could make it (C) 2024 at the next update.

**Comment by ypriverol** [comment]
What means `(C) 2024`?

**Comment by edeutsch** [comment]
Copyright notice at the bottom of the page is (C) 2023. But it's now 2024

**Comment by javizca** [comment]
This looks great
@ypriverol, the URL should change to https://www.proteomexchange.org/ptmexchange/index.html

with an extra 'e'

**Comment by ypriverol** [comment]
Both small issues are now solved.

**Comment by isbluis** [comment]
Looks great, many thanks for your help!

**Comment by isbluis** [comment]
Hello @ypriverol .  I made a small change to correct the PXD identifiers in the PTMX index page; can you please redeploy when you are able to?
Thanks!

**Comment by ypriverol** [comment]
Hi Luis, all changes are now deployed. I will close the issue.
